name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-run-and-test:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: TesteApi.sln
      Test_Unit_Project_Path: TesteApiUnitTest\TesteApiUnitTest.csproj
      

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      run: dotnet restore ${{ env.Solution_Name }}


    - name: Run unit tests
      run: dotnet test ${{ env.Test_Unit_Project_Path }}

